### ISSUE TITLE
Question about the logger

### ISSUE THREAD

**Issue by Ratstail91** [Moosader/Kuko#29]
Hey, I'm poking around in this engine and nitpicking to myself, and I noticed this line in [Logger.cpp](https://github.com/Moosader/Kuko/blob/master/utilities/Logger.cpp#L134):

```
std::cerr << "\t LINE " << __LINE__ << " FILE " << __FILE__ ;
```

Does this actually work as intended? As far as I know, it would simply output this every time:

```
    LINE 134 FILE Logger.cpp
```

Maybe you were trying to refer to the line where Logger::Error() was called?

**Comment by NicePixel** [comment]
Yep, that doesn't look quite right. Perhaps the subroutine can be changed to take two additional parameters, one for the line number and one for the file.

**Comment by Rejcx** [comment]
That's correct, but I'm not currently relying on that code to tell me where the location of the file is. I just have not removed it yet.

**Comment by Ratstail91** [comment]
Incomplete and legacy code like this drives me nuts. And [global singletons](https://github.com/Moosader/Kuko/tree/master/managers). And [specialized base classes](https://github.com/Moosader/Kuko/blob/master/widgets/UIImage.cpp#L60). And working with other people's code in general, sorry.
